after_success:
  - codecov
  - pylint --output-format=text app/
branches:
  only:
    - master
cache: pip
install:
  - pip install -r requirements.txt
  - pip install codecov
language: python
python:
  - 3.6
script:
  - coverage erase
  - coverage run -m pytest && coverage html
